INSERT INTO brinquedo (categoria, codigo, descricao, detalhes, imagem, marca, quant_vendas, valor) VALUES
('Veiculos', 1001, 'Carrinho Controle Remoto', 'Carrinho elétrico com controle remoto de 4 canais.', 'https://i.imgur.com/67DJRFB.png', 'HotWheels', 120, 149.9),
('Bonecas', 1002, 'Boneca Fashion', 'Boneca articulada com roupas e acessórios inclusos.', 'https://i.imgur.com/CiRJA6Y.png', 'Barbie', 300, 89.9),
('Blocos de montar', 1003, 'Jogo Blocos Criativos', 'Kit com 500 peças para montar diferentes estruturas.', 'https://i.imgur.com/8X84Mjl.png', 'Lego', 250, 199.9),
('Pelucia', 1004, 'Urso de Pelúcia Gigante', 'Urso de pelúcia macio com 50 cm de altura.', 'https://i.imgur.com/upvtkc8.png', 'Fofuxo', 80, 59.9),
('Jogos e Tabuleiro', 1005, 'Quebra-Cabeça 1000 Peças', 'Quebra-cabeça de 1000 peças com imagem de paisagem.', 'https://rihappy.vtexassets.com/arquivos/ids/3053532-1600-auto?v=637860823552370000&width=1600&height=auto&aspect=true', 'Grow', 150, 69.9),
('Veiculos', 1006, 'Pista de Carrinhos', 'Pista com loopings e dois carrinhos inclusos.', 'https://i.imgur.com/dkSWmBB.png', 'HotWheels', 210, 179.9),
('Jogos e Tabuleiro', 1007, 'Tabuleiro Banco Imobiliário', 'Clássico jogo de tabuleiro de compra e venda de imóveis.', 'https://i.imgur.com/RGbQ71a.png', 'Estrela', 400, 99.9),
('Diversos', 1008, 'Kit Médico Infantil', 'Mala com acessórios de médico para brincar de faz de conta.', 'https://i.imgur.com/GmIICs8.png', 'DiverKids', 75, 49.9),
('Esportivos', 1009, 'Bola Futebol Infantil', 'Bola de futebol tamanho infantil, material resistente.', 'https://i.imgur.com/zwzpcxS.png', 'Penalty', 330, 59.9),
('Esportivos', 1010, 'Patinete Dobrável', 'Patinete leve e dobrável para crianças até 12 anos.', 'https://i.imgur.com/mRKZwyq.png', 'Xtreme', 190, 229.9),
('Bonecos', 1011, 'Boneco Super-Man', 'Boneco articulado com 30 cm de altura.', 'https://i.imgur.com/34UJ1hL.png', 'Marvel', 410, 79.9),
('Diversos', 1012, 'Kit Massinha de Modelar', 'Kit com 10 potes de massinha colorida e moldes inclusos.', 'https://i.imgur.com/4loZ49Q.png', 'Play-Doh', 500, 39.9),
('Diversos', 1013, 'Mini Cozinha Infantil', 'Cozinha infantil com utensílios e fogão.', 'https://i.imgur.com/pqjDEDW.png', 'DiverKids', 120, 159.9),
('Diversos', 1014, 'Robô Interativo', 'Robô com comandos de voz e movimentos programáveis.', 'https://i.imgur.com/NfAdqcw.png', 'TechToy', 60, 299.9),
('Bonecos', 1015, 'Kit Dinossauros', 'Kit com 5 dinossauros em miniatura.', 'https://images.tcdn.com.br/img/img_prod/1142755/kit_2_dinossauros_de_brinquedo_monta_e_desmonta_rs046_2a_doremi_25762_1_c207b9e93d364a798ef986c46933818c.jpg', 'Jurassic', 200, 89.9),
('Bonecas', 1016, 'Castelo de Princesa', 'Castelo com torres, móveis e espaço para bonecas.', 'https://images.tcdn.com.br/img/img_prod/1100427/90_brinquedo_infantil_castelo_de_princesas_maral_361_3_872e324e34d052960b30ecff575f6c0d.jpg', 'Barbie', 95, 349.9),
('Diversos', 1017, 'Violão Infantil', 'Violão infantil em madeira com cordas de nylon.', 'https://i.imgur.com/e1unv49.png', 'MiniMusic', 130, 129.9),
('Esportivos', 1018, 'Patins Inline', 'Patins ajustável com rodinhas em linha.', 'https://i.imgur.com/7T29Bpx.png', 'RollerFun', 140, 259.9),
('Esportivos', 1019, 'Bicicleta Aro 16', 'Bicicleta infantil aro 16 com rodinhas removíveis.', 'https://i.imgur.com/gh3fWuZ.png', 'Caloi', 220, 599.9),
('Jogos e Tabuleiro', 1020, 'Jogo de Cartas Uno', 'Clássico jogo de cartas para toda família.', 'https://i.imgur.com/Pi6JTkf.png', 'Mattel', 1000, 34.9),
('Bonecos', 1021, 'Boneco Wolverine', 'Boneco com múltiplos pontos de articulação e garras retráteis.', 'https://i.imgur.com/KqdAYrO.png', 'Hasbro', 55, 119.9),
('Bonecos', 1022, 'Boneco Flash', 'Figura de ação com traje detalhado e super velocidade.', 'https://i.imgur.com/FVNG8CS.png', 'Bandai', 80, 99.9),
('Bonecos', 1023, 'Boneco Capitão América', 'Acompanha escudo com acessório de lançamento.', 'https://i.imgur.com/p53xpTx.png', 'Mattel', 70, 109.9),
('Bonecos', 1024, 'Boneco Thor', 'Figura de ação com capa removível e o martelo Mjolnir.', 'https://i.imgur.com/V6GGBOW.png', 'Hasbro', 65, 119.9),
('Bonecos', 1025, 'Conjunto DC Comics', 'Kit com os heróis Super-Homem, Batman e Flash.', 'https://i.imgur.com/gbHdGt0.png', 'Sunny', 150, 199.9),
('Bonecos', 1026, 'Boneco Pantera Negra', 'Figura de ação com traje vibranium, 12 pontos de articulação.', 'https://i.imgur.com/idEK7Io.png', 'Hasbro', 90, 105.9),
('Bonecos', 1027, 'Funko Pop Ayrton Sena', 'Colecionável Funko Pop do lendário piloto de F1.', 'https://i.imgur.com/5zChOBa.png', 'Funko Pop', 250, 149.9),
('Bonecos', 1028, 'Optimus Prime', 'Robô que se transforma em caminhão em 15 passos.', 'https://i.imgur.com/YWzrLKG.png', 'Transformers', 110, 249.9),
('Bonecos', 1029, 'Robô Pacific Rim', 'Boneco articulado de 30cm, fiel ao filme Pacific Rim.', 'https://i.imgur.com/epUptZe.png', 'Jazwares', 45, 189.9),
('Bonecos', 1030, 'Boneco Buzz Lightyear', 'Figura de ação com luzes e sons, asa retrátil.', 'https://i.imgur.com/ebuQIvX.png', 'Toyng', 200, 139.9),
('Bonecos', 1031, 'Boneco Homem-Aranha', 'Com lança-teia removível e 5 pontos de articulação.', 'https://i.imgur.com/fcoGtDn.png', 'Hasbro', 185, 95.9),
('Esportivos', 1032, 'Bicicleta Aro 24 Nathor', 'Bicicleta infantil com design moderno, ideal para meninas. Cor: Branca e pink.', 'https://i.imgur.com/0lLkkT0.png', 'Nathor', 30, 650.0),
('Esportivos', 1033, 'Bicicleta Aro 24 Caloi', 'Bicicleta com 21 velocidades e suspensão dianteira. Cor: Branca e vermelha.', 'https://i.imgur.com/TOowIak.png', 'Caloi', 45, 899.9),
('Esportivos', 1034, 'Bola Futebol de Campo', 'Bola de futebol profissional, costurada à mão.', 'https://i.imgur.com/SCUN0sV.png', 'Penalty', 350, 79.9),
('Esportivos', 1035, 'Pula Pula Pogobol', 'Clássico brinquedo Pogobol para saltar e brincar.', 'https://i.imgur.com/TMY13ea.png', 'Estrela', 180, 159.9),
('Esportivos', 1036, 'Mini Bola de Basquete', 'Mini bola de borracha, ideal para crianças e jogos em casa.', 'https://i.imgur.com/PZEM47Z.png', 'Spalding', 120, 45.9),
('Esportivos', 1037, 'Skate Jurassic World', 'Skate infantil com estampa do filme Jurassic World.', 'https://i.imgur.com/dK7OoEb.png', 'DM Toys', 60, 149.9),
('Esportivos', 1038, 'Skatenet Ajustável', 'Patina com três rodas e altura ajustável do guidão.', 'https://i.imgur.com/R4fn96O.png', 'Bandeirante', 95, 189.9),
('Esportivos', 1039, 'Triciclo Infantil', 'Triciclo com assento confortável e cestinha na frente. Cores: amarelo e azul.', 'https://i.imgur.com/QYsL7QZ.png', 'Homeplay', 85, 199.9),
('Esportivos', 1040, 'Triciclo para 3', 'Triciclo com dois assentos traseiros para carregar amigos.', 'https://i.imgur.com/Zcr9ix5.png', 'Mundo Trike', 20, 599.9),
('Esportivos', 1041, 'Tabela de Basquete NBA', 'Tabela de basquete portátil com aro e rede, tema NBA.', 'https://i.imgur.com/Pfrcc5m.png', 'FischerPrice', 110, 229.9),
('Esportivos', 1042, 'Patins Infantil', 'Patins com rodinhas coloridas e freio traseiro.', 'https://i.imgur.com/wp4e8dq.png', 'Fun Divirta-se', 140, 249.9),
('Esportivos', 1043, 'Patins com Luzes', 'Patins com cano alto para maior estabilidade e segurança. Rodas que iluminam.', 'https://i.imgur.com/2nAe4wx.png', 'Oxelo', 155, 279.9),
('Esportivos', 1044, 'Trave Chute a Gol', 'Trave de futebol infantil com estampa do Homem-Aranha.', 'https://i.imgur.com/PIoL3jg.png', 'Lider Brinquedos', 90, 119.9),
('Pelucia', 1045, 'Pelúcia Aprender e Brincar', 'Pelúcia interativa que ensina letras, cores e números.', 'https://i.imgur.com/auYflxw.png', 'Fisher Price', 180, 129.9),
('Pelucia', 1046, 'Pelúcia Patrulha Canina', 'Pelúcia macia do personagem Chase, da Patrulha Canina.', 'https://i.imgur.com/efP0MUf.png', 'Sunny', 210, 69.9),
('Pelucia', 1047, 'Pelúcia Série Bluey', 'Pelúcia do personagem Bluey, da série de TV.', 'https://i.imgur.com/Vtlzjib.png', 'Long Jump', 175, 79.9),
('Pelucia', 1048, 'Sr. Batata 13 Peças', 'Conjunto com 13 peças para montar o Sr. Batata.', 'https://i.imgur.com/ireFn3a.png', 'Hasbro', 130, 89.9),
('Pelucia', 1049, 'Patinho de Pelúcia', 'Patinho de pelúcia amarelo e macio, 20 cm.', 'https://i.imgur.com/IXnhdCt.png', 'Fofuxo', 100, 45.9),
('Pelucia', 1050, 'Urso de Pelúcia Médio', 'Urso de pelúcia com laço no pescoço, 30 cm de altura.', 'https://i.imgur.com/HWC6z7F.png', 'Fofuxo', 150, 79.9),
('Veiculos', 1052, 'Carrinho Polícia', 'Carrinho de brinquedo com sirene e luzes de LED.', 'https://i.imgur.com/uAZRAXL.png', 'Roma Brinquedos', 190, 89.9),
('Veiculos', 1053, 'Carros Sortidos', 'Miniaturas de carros de diversos modelos. Venda por unidade.', 'https://i.imgur.com/CRXdDSl.png', 'HotWheels', 300, 19.9),
('Veiculos', 1054, 'Ferrari Vermelha', 'Carrinho miniatura de metal, réplica da Ferrari 488.', 'https://i.imgur.com/gltdusg.png', 'Maisto', 120, 59.9),
('Veiculos', 1055, 'McLaren 570S Laranja', 'Carrinho miniatura de metal, réplica da McLaren 570S.', 'https://i.imgur.com/EK9PoUi.png', 'Burago', 100, 59.9),
('Veiculos', 1056, 'Mega Pista Carrinhos', 'Pista com loopings, elevador e espaço para 50 carrinhos.', 'https://i.imgur.com/kTYp0lR.png', 'HotWheels', 70, 299.9),
('Veiculos', 1057, 'Pista Hot Wheels', 'Pista de corrida com lançador de carros.', 'https://i.imgur.com/r99fIhO.png', 'HotWheels', 180, 169.9),
('Veiculos', 1058, 'Super Jipe Passeio', 'Jipe de passeio com pedal e haste para empurrar.', 'https://i.imgur.com/vdaQqet.png', 'Bandeirante', 50, 389.9),
('Veiculos', 1059, 'Carrinho Controle Remoto CKS', 'Carrinho de controle remoto com bateria recarregável.', 'https://i.imgur.com/Y6qO2Xx.png', 'CKS Toys', 110, 139.9),
('Veiculos', 1060, 'Avião Aeromodelo', 'Miniaturas de avião para colecionar, vários modelos.', 'https://i.imgur.com/q5VPyon.png', 'Estrela', 95, 49.9),
('Veiculos', 1061, 'Avião de Brinquedo', 'Avião de plástico colorido, com hélice giratória.', 'https://i.imgur.com/iOrs1f3.png', 'Roma Brinquedos', 80, 59.9),
('Veiculos', 1062, 'Trem de Madeira', 'Trem de brinquedo com locomotiva e 3 vagões.', 'https://i.imgur.com/sUCVeYS.png', 'Brincadeira de Criança', 65, 119.9),
('Bonecas', 1063, 'Barbie Disco Start', 'Boneca Barbie com roupa brilhante inspirada na era disco.', 'https://i.imgur.com/QspToG4.png', 'Mattel', 130, 129.9),
('Bonecas', 1064, 'Barbie Sereia', 'Boneca Barbie com cauda de sereia e cabelo colorido.', 'https://i.imgur.com/snNE5v1.png', 'Mattel', 160, 149.9),
('Diversos', 1065, 'Cavalinho Balancinho', 'Cavalinho de madeira para balançar, pintado à mão.', 'https://i.imgur.com/TOmBozA.png', 'Simba', 40, 219.9),
('Diversos', 1066, 'Rádio Comunicação', 'Kit de rádio comunicador para brincar de detetive.', 'https://i.imgur.com/EfB5gly.png', 'Buba Toys', 75, 119.9),
('Diversos', 1067, 'Navio de Madeira', 'Miniatura de navio em madeira, ideal para decoração.', 'https://i.imgur.com/A8nZ6da.png', 'Estrela', 30, 99.9),
('Diversos', 1068, 'Robô AT-ST Star Wars', 'Robô AT-ST do universo Star Wars com detalhes precisos.', 'https://i.imgur.com/k4mnLbg.png', 'Hasbro', 95, 189.9),
('Diversos', 1069, 'Violão Infantil Nylon', 'Violão de brinquedo com cordas de nylon, para iniciantes.', 'https://i.imgur.com/YwdcDwY.png', 'Art Brink', 105, 109.9);