INSERT INTO brinquedo (codigo, descricao, categoria, marca, imagem, valor, detalhes, quantVendas) VALUES
(1001, 'Carrinho Controle Remoto', 'Veiculos', 'HotWheels', 'https://i.imgur.com/67DJRFB.png', 149.9, 'Carrinho elétrico com controle remoto de 4 canais.', 120),
(1002, 'Boneca Fashion', 'Bonecas', 'Barbie', 'https://i.imgur.com/CiRJA6Y.png', 89.9, 'Boneca articulada com roupas e acessórios inclusos.', 300),
(1003, 'Jogo Blocos Criativos', 'Blocos de montar', 'Lego', 'https://i.imgur.com/8X84Mjl.png', 199.9, 'Kit com 500 peças para montar diferentes estruturas.', 250),
(1004, 'Urso de Pelúcia Gigante', 'Pelucia', 'Fofuxo', 'https://i.imgur.com/upvtkc8.png', 59.9, 'Urso de pelúcia macio com 50 cm de altura.', 80),
(1005, 'Quebra-Cabeça 1000 Peças', 'Jogos e Tabuleiro', 'Grow', 'https://rihappy.vtexassets.com/arquivos/ids/3053532-1600-auto?v=637860823552370000&width=1600&height=auto&aspect=true', 69.9, 'Quebra-cabeça de 1000 peças com imagem de paisagem.', 150),
(1006, 'Pista de Carrinhos', 'Veiculos', 'HotWheels', 'https://i.imgur.com/dkSWmBB.png', 179.9, 'Pista com loopings e dois carrinhos inclusos.', 210),
(1007, 'Tabuleiro Banco Imobiliário', 'Jogos e Tabuleiro', 'Estrela', 'https://i.imgur.com/RGbQ71a.png', 99.9, 'Clássico jogo de tabuleiro de compra e venda de imóveis.', 400),
(1008, 'Kit Médico Infantil', 'Diversos', 'DiverKids', 'https://i.imgur.com/GmIICs8.png', 49.9, 'Mala com acessórios de médico para brincar de faz de conta.', 75),
(1009, 'Bola Futebol Infantil', 'Esportivos', 'Penalty', 'https://i.imgur.com/zwzpcxS.png', 59.9, 'Bola de futebol tamanho infantil, material resistente.', 330),
(1010, 'Patinete Dobrável', 'Esportivos', 'Xtreme', 'https://i.imgur.com/mRKZwyq.png', 229.9, 'Patinete leve e dobrável para crianças até 12 anos.', 190),
(1011, 'Boneco Super-Man', 'Bonecos', 'Marvel', 'https://i.imgur.com/34UJ1hL.png', 79.9, 'Boneco articulado com 30 cm de altura.', 410),
(1012, 'Kit Massinha de Modelar', 'Diversos', 'Play-Doh', 'https://i.imgur.com/4loZ49Q.png', 39.9, 'Kit com 10 potes de massinha colorida e moldes inclusos.', 500),
(1013, 'Mini Cozinha Infantil', 'Diversos', 'DiverKids', 'https://i.imgur.com/pqjDEDW.png', 159.9, 'Cozinha infantil com utensílios e fogão.', 120),
(1014, 'Robô Interativo', 'Diversos', 'TechToy', 'https://i.imgur.com/NfAdqcw.png', 299.9, 'Robô com comandos de voz e movimentos programáveis.', 60),
(1015, 'Kit Dinossauros', 'Bonecos', 'Jurassic', 'https://images.tcdn.com.br/img/img_prod/1142755/kit_2_dinossauros_de_brinquedo_monta_e_desmonta_rs046_2a_doremi_25762_1_c207b9e93d364a798ef986c46933818c.jpg', 89.9, 'Kit com 5 dinossauros em miniatura.', 200),
(1016, 'Castelo de Princesa', 'Bonecas', 'Barbie', 'https://images.tcdn.com.br/img/img_prod/1100427/90_brinquedo_infantil_castelo_de_princesas_maral_361_3_872e324e34d052960b30ecff575f6c0d.jpg', 349.9, 'Castelo com torres, móveis e espaço para bonecas.', 95),
(1017, 'Violão Infantil', 'Diversos', 'MiniMusic', 'https://i.imgur.com/e1unv49.png', 129.9, 'Violão infantil em madeira com cordas de nylon.', 130),
(1018, 'Patins Inline', 'Esportivos', 'RollerFun', 'https://i.imgur.com/7T29Bpx.png', 259.9, 'Patins ajustável com rodinhas em linha.', 140),
(1019, 'Bicicleta Aro 16', 'Esportivos', 'Caloi', 'https://i.imgur.com/gh3fWuZ.png', 599.9, 'Bicicleta infantil aro 16 com rodinhas removíveis.', 220),
(1020, 'Jogo de Cartas Uno', 'Jogos e Tabuleiro', 'Mattel', 'https://i.imgur.com/Pi6JTkf.png', 34.9, 'Clássico jogo de cartas para toda família.', 1000),
(1021, 'Boneco Wolverine', 'Bonecos', 'Hasbro', 'https://i.imgur.com/KqdAYrO.png', 119.9, 'Boneco com múltiplos pontos de articulação e garras retráteis.', 55),
(1022, 'Boneco Flash', 'Bonecos', 'Bandai', 'https://i.imgur.com/FVNG8CS.png', 99.9, 'Figura de ação com traje detalhado e super velocidade.', 80),
(1023, 'Boneco Capitão América', 'Bonecos', 'Mattel', 'https://i.imgur.com/p53xpTx.png', 109.9, 'Acompanha escudo com acessório de lançamento.', 70),
(1024, 'Boneco Thor', 'Bonecos', 'Hasbro', 'https://i.imgur.com/V6GGBOW.png', 119.9, 'Figura de ação com capa removível e o martelo Mjolnir.', 65),
(1025, 'Conjunto DC Comics', 'Bonecos', 'Sunny', 'https://i.imgur.com/gbHdGt0.png', 199.9, 'Kit com os heróis Super-Homem, Batman e Flash.', 150),
(1026, 'Boneco Pantera Negra', 'Bonecos', 'Hasbro', 'https://i.imgur.com/idEK7Io.png', 105.9, 'Figura de ação com traje vibranium, 12 pontos de articulação.', 90),
(1027, 'Funko Pop Ayrton Sena', 'Bonecos', 'Funko Pop', 'https://i.imgur.com/5zChOBa.png', 149.9, 'Colecionável Funko Pop do lendário piloto de F1.', 250),
(1028, 'Optimus Prime', 'Bonecos', 'Transformers', 'https://i.imgur.com/YWzrLKG.png', 249.9, 'Robô que se transforma em caminhão em 15 passos.', 110),
(1029, 'Robô Pacific Rim', 'Bonecos', 'Jazwares', 'https://i.imgur.com/epUptZe.png', 189.9, 'Boneco articulado de 30cm, fiel ao filme Pacific Rim.', 45),
(1030, 'Boneco Buzz Lightyear', 'Bonecos', 'Toyng', 'https://i.imgur.com/ebuQIvX.png', 139.9, 'Figura de ação com luzes e sons, asa retrátil.', 200),
(1031, 'Boneco Homem-Aranha', 'Bonecos', 'Hasbro', 'https://i.imgur.com/fcoGtDn.png', 95.9, 'Com lança-teia removível e 5 pontos de articulação.', 185),
(1032, 'Bicicleta Aro 24 Nathor', 'Esportivos', 'Nathor', 'https://i.imgur.com/0lLkkT0.png', 650.0, 'Bicicleta infantil com design moderno, ideal para meninas. Cor: Branca e pink.', 30),
(1033, 'Bicicleta Aro 24 Caloi', 'Esportivos', 'Caloi', 'https://i.imgur.com/TOowIak.png', 899.9, 'Bicicleta com 21 velocidades e suspensão dianteira. Cor: Branca e vermelha.', 45),
(1034, 'Bola Futebol de Campo', 'Esportivos', 'Penalty', 'https://i.imgur.com/SCUN0sV.png', 79.9, 'Bola de futebol profissional, costurada à mão.', 350),
(1035, 'Pula Pula Pogobol', 'Esportivos', 'Estrela', 'https://i.imgur.com/TMY13ea.png', 159.9, 'Clássico brinquedo Pogobol para saltar e brincar.', 180),
(1036, 'Mini Bola de Basquete', 'Esportivos', 'Spalding', 'https://i.imgur.com/PZEM47Z.png', 45.9, 'Mini bola de borracha, ideal para crianças e jogos em casa.', 120),
(1037, 'Skate Jurassic World', 'Esportivos', 'DM Toys', 'https://i.imgur.com/dK7OoEb.png', 149.9, 'Skate infantil com estampa do filme Jurassic World.', 60),
(1038, 'Skatenet Ajustável', 'Esportivos', 'Bandeirante', 'https://i.imgur.com/R4fn96O.png', 189.9, 'Patina com três rodas e altura ajustável do guidão.', 95),
(1039, 'Triciclo Infantil', 'Esportivos', 'Homeplay', 'https://i.imgur.com/QYsL7QZ.png', 199.9, 'Triciclo com assento confortável e cestinha na frente. Cores: amarelo e azul.', 85),
(1040, 'Triciclo para 3', 'Esportivos', 'Mundo Trike', 'https://i.imgur.com/Zcr9ix5.png', 599.9, 'Triciclo com dois assentos traseiros para carregar amigos.', 20),
(1041, 'Tabela de Basquete NBA', 'Esportivos', 'FischerPrice', 'https://i.imgur.com/Pfrcc5m.png', 229.9, 'Tabela de basquete portátil com aro e rede, tema NBA.', 110),
(1042, 'Patins Infantil', 'Esportivos', 'Fun Divirta-se', 'https://i.imgur.com/wp4e8dq.png', 249.9, 'Patins com rodinhas coloridas e freio traseiro.', 140),
(1043, 'Patins com Luzes', 'Esportivos', 'Oxelo', 'https://i.imgur.com/2nAe4wx.png', 279.9, 'Patins com cano alto para maior estabilidade e segurança. Rodas que iluminam.', 155),
(1044, 'Trave Chute a Gol', 'Esportivos', 'Lider Brinquedos', 'https://i.imgur.com/PIoL3jg.png', 119.9, 'Trave de futebol infantil com estampa do Homem-Aranha.', 90),
(1045, 'Pelúcia Aprender e Brincar', 'Pelucia', 'Fisher Price', 'https://i.imgur.com/auYflxw.png', 129.9, 'Pelúcia interativa que ensina letras, cores e números.', 180),
(1046, 'Pelúcia Patrulha Canina', 'Pelucia', 'Sunny', 'https://i.imgur.com/efP0MUf.png', 69.9, 'Pelúcia macia do personagem Chase, da Patrulha Canina.', 210),
(1047, 'Pelúcia Série Bluey', 'Pelucia', 'Long Jump', 'https://i.imgur.com/Vtlzjib.png', 79.9, 'Pelúcia do personagem Bluey, da série de TV.', 175),
(1048, 'Sr. Batata 13 Peças', 'Pelucia', 'Hasbro', 'https://i.imgur.com/ireFn3a.png', 89.9, 'Conjunto com 13 peças para montar o Sr. Batata.', 130),
(1049, 'Patinho de Pelúcia', 'Pelucia', 'Fofuxo', 'https://i.imgur.com/IXnhdCt.png', 45.9, 'Patinho de pelúcia amarelo e macio, 20 cm.', 100),
(1050, 'Urso de Pelúcia Médio', 'Pelucia', 'Fofuxo', 'https://i.imgur.com/HWC6z7F.png', 79.9, 'Urso de pelúcia com laço no pescoço, 30 cm de altura.', 150),
(1051, 'T-Rex de Pelúcia', 'Pelucia', 'Tricae', 'https://i.imgur.com/zoQ2dnX.png', 99.9, 'Dinossauro T-Rex de pelúcia com detalhes realistas.', 80),
(1052, 'Carrinho Polícia', 'Veiculos', 'Roma Brinquedos', 'https://i.imgur.com/uAZRAXL.png', 89.9, 'Carrinho de brinquedo com sirene e luzes de LED.', 190),
(1053, 'Carros Sortidos', 'Veiculos', 'HotWheels', 'https://i.imgur.com/CRXdDSl.png', 19.9, 'Miniaturas de carros de diversos modelos. Venda por unidade.', 300),
(1054, 'Ferrari Vermelha', 'Veiculos', 'Maisto', 'https://i.imgur.com/gltdusg.png', 59.9, 'Carrinho miniatura de metal, réplica da Ferrari 488.', 120),
(1055, 'McLaren 570S Laranja', 'Veiculos', 'Burago', 'https://i.imgur.com/EK9PoUi.png', 59.9, 'Carrinho miniatura de metal, réplica da McLaren 570S.', 100),
(1056, 'Mega Pista Carrinhos', 'Veiculos', 'HotWheels', 'https://i.imgur.com/kTYp0lR.png', 299.9, 'Pista com loopings, elevador e espaço para 50 carrinhos.', 70),
(1057, 'Pista Hot Wheels', 'Veiculos', 'HotWheels', 'https://i.imgur.com/r99fIhO.png', 169.9, 'Pista de corrida com lançador de carros.', 180),
(1058, 'Super Jipe Passeio', 'Veiculos', 'Bandeirante', 'https://i.imgur.com/vdaQqet.png', 389.9, 'Jipe de passeio com pedal e haste para empurrar.', 50),
(1059, 'Carrinho Controle Remoto CKS', 'Veiculos', 'CKS Toys', 'https://i.imgur.com/Y6qO2Xx.png', 139.9, 'Carrinho de controle remoto com bateria recarregável.', 110),
(1060, 'Avião Aeromodelo', 'Veiculos', 'Estrela', 'https://i.imgur.com/q5VPyon.png', 49.9, 'Miniaturas de avião para colecionar, vários modelos.', 95),
(1061, 'Avião de Brinquedo', 'Veiculos', 'Roma Brinquedos', 'https://i.imgur.com/iOrs1f3.png', 59.9, 'Avião de plástico colorido, com hélice giratória.', 80),
(1062, 'Trem de Madeira', 'Veiculos', 'Brincadeira de Criança', 'https://i.imgur.com/sUCVeYS.png', 119.9, 'Trem de brinquedo com locomotiva e 3 vagões.', 65),
(1063, 'Barbie Disco Start', 'Bonecas', 'Mattel', 'https://i.imgur.com/QspToG4.png', 129.9, 'Boneca Barbie com roupa brilhante inspirada na era disco.', 130),
(1064, 'Barbie Sereia', 'Bonecas', 'Mattel', 'https://i.imgur.com/snNE5v1.png', 149.9, 'Boneca Barbie com cauda de sereia e cabelo colorido.', 160),
(1065, 'Cavalinho Balancinho', 'Diversos', 'Simba', 'https://i.imgur.com/TOmBozA.png', 219.9, 'Cavalinho de madeira para balançar, pintado à mão.', 40),
(1066, 'Rádio Comunicação', 'Diversos', 'Buba Toys', 'https://i.imgur.com/EfB5gly.png', 119.9, 'Kit de rádio comunicador para brincar de detetive.', 75),
(1067, 'Navio de Madeira', 'Diversos', 'Estrela', 'https://i.imgur.com/A8nZ6da.png', 99.9, 'Miniatura de navio em madeira, ideal para decoração.', 30),
(1068, 'Robô AT-ST Star Wars', 'Diversos', 'Hasbro', 'https://i.imgur.com/k4mnLbg.png', 189.9, 'Robô AT-ST do universo Star Wars com detalhes precisos.', 95),
(1069, 'Violão Infantil Nylon', 'Diversos', 'Art Brink', 'https://i.imgur.com/YwdcDwY.png', 109.9, 'Violão de brinquedo com cordas de nylon, para iniciantes.', 105);



INSERT INTO usuario (nome, userEmail, userSenha) VALUES
('Gilson', 'gilson-email@mail.com', 'teste1'),
('Maikon', 'maikon-email@mail.com', 'teste2'),
('Mateus', 'mateus-email@mail.com', 'teste3');
